export const loginTranslations = {
  EN: {
    badge: "AI customer support platform",
    heroTitle: "Welcome back to your support workspace",
    heroText: "Manage conversations, products, guidance and AI actions from one dashboard.",
    heroFooter: "Built for fast support teams",
    title: "Welcome back",
    subtitle: "Log in to your TODO account",
    namePlaceholder: "Full name",
    emailPlaceholder: "Your work email",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot password?",
    submit: "Log In",
    divider: "or",
    forgotTitle: "Password Reset",
    forgotSubtitle: "Enter your email address",
    forgotEmailPlaceholder: "Email address",
    forgotSend: "Send Link",
    forgotBack: "Back to login",
    forgotSuccess: "If the email exists, a reset link will be sent",
    resetTitle: "Reset Password",
    resetSubtitle: "Enter your new password",
    resetPlaceholder: "New password (min 8 chars)",
    resetSubmit: "Reset Password",
    resetBack: "Back to login",
    resetSuccess: "Password reset successfully. Redirecting to login...",
    resetError: "Invalid or expired link",
    resetShortPassword: "Password must be at least 8 characters",
  },
  TR: {
    badge: "Yapay zeka müşteri destek platformu",
    heroTitle: "Destek çalışma alanına tekrar hoş geldin",
    heroText: "Görüşmeleri, ürünleri, yönlendirmeleri ve AI aksiyonlarını tek panelden yönet.",
    heroFooter: "Hızlı destek ekipleri için geliştirildi",
    title: "Tekrar hoş geldin",
    subtitle: "TODO hesabına giriş yap",
    namePlaceholder: "Ad Soyad",
    emailPlaceholder: "İş e-posta adresin",
    passwordPlaceholder: "Şifre",
    forgotPassword: "Şifreni mi unuttun?",
    submit: "Giriş Yap",
    divider: "veya",
    forgotTitle: "Şifre Sıfırlama",
    forgotSubtitle: "E-posta adresinizi girin",
    forgotEmailPlaceholder: "E-posta adresi",
    forgotSend: "Link Gönder",
    forgotBack: "Girişe dön",
    forgotSuccess: "E-posta mevcutsa, sıfırlama linki gönderilecek",
    resetTitle: "Şifre Sıfırla",
    resetSubtitle: "Yeni şifrenizi girin",
    resetPlaceholder: "Yeni şifre (min 8 karakter)",
    resetSubmit: "Şifreyi Sıfırla",
    resetBack: "Girişe dön",
    resetSuccess: "Şifre başarıyla sıfırlandı. Girişe yönlendiriliyor...",
    resetError: "Geçersiz veya süresi geçmiş link",
    resetShortPassword: "Şifre en az 8 karakter olmalıdır",
  },
  AZ: {
    badge: "AI müştəri dəstək platforması",
    heroTitle: "Dəstək iş məkanına yenidən xoş gəldin",
    heroText: "Mesajları, məhsulları, guidance hissəsini və AI action-ları tək paneldən idarə et.",
    heroFooter: "Sürətli dəstək komandaları üçün hazırlanıb",
    title: "Yenidən xoş gəldin",
    subtitle: "TODO hesabına daxil ol",
    namePlaceholder: "Ad və soyad",
    emailPlaceholder: "İş e-poçtun",
    passwordPlaceholder: "Şifrə",
    forgotPassword: "Şifrəni unutmusan?",
    submit: "Daxil ol",
    divider: "və ya",
    forgotTitle: "Şifrə Sıfırlama",
    forgotSubtitle: "Email ünvanınızı daxil edin",
    forgotEmailPlaceholder: "Email ünvanı",
    forgotSend: "Link Göndər",
    forgotBack: "Girişə qayıt",
    forgotSuccess: "Əgər email mövcuddursa, reset linki göndəriləcək",
    resetTitle: "Şifrə Sıfırlama",
    resetSubtitle: "Yeni şifrənizi daxil edin",
    resetPlaceholder: "Yeni şifrə (min 8 simvol)",
    resetSubmit: "Şifrəni Sıfırla",
    resetBack: "Girişə qayıt",
    resetSuccess: "Şifrə uğurla sıfırlandı. Giriş səhifəsinə yönləndirilir...",
    resetError: "Yanlış və ya vaxtı keçmiş link",
    resetShortPassword: "Şifrə ən azı 8 simvol olmalıdır",
  },
  RU: {
    badge: "Платформа AI поддержки клиентов",
    heroTitle: "С возвращением в рабочее пространство поддержки",
    heroText: "Управляйте разговорами, товарами, руководствами и действиями AI с одной панели.",
    heroFooter: "Создано для быстрых команд поддержки",
    title: "С возвращением",
    subtitle: "Войдите в свой аккаунт TODO",
    namePlaceholder: "Полное имя",
    emailPlaceholder: "Ваш рабочий email",
    passwordPlaceholder: "Пароль",
    forgotPassword: "Забыли пароль?",
    submit: "Войти",
    divider: "или",
    forgotTitle: "Сброс пароля",
    forgotSubtitle: "Введите ваш email",
    forgotEmailPlaceholder: "Email адрес",
    forgotSend: "Отправить ссылку",
    forgotBack: "Вернуться к входу",
    forgotSuccess: "Если email существует, ссылка будет отправлена",
    resetTitle: "Сброс пароля",
    resetSubtitle: "Введите новый пароль",
    resetPlaceholder: "Новый пароль (мин 8 символов)",
    resetSubmit: "Сбросить пароль",
    resetBack: "Вернуться к входу",
    resetSuccess: "Пароль успешно сброшен. Перенаправление на вход...",
    resetError: "Недействительная или просроченная ссылка",
    resetShortPassword: "Пароль должен быть минимум 8 символов",
  },
};
