export const adminNavItems = [
  { key: "dashboard", label: "Dashboard", icon: "dashboard" },
  { key: "knowledge", label: "Knowledge", caret: true, icon: "knowledge" },
  { key: "data-sources", label: "Data sources", nested: true, icon: "data-sources" },
  { key: "products", label: "Products", nested: true, icon: "products" },
  { key: "suggestions", label: "Suggestions", nested: true, icon: "suggestions" },
  { key: "playground", label: "Playground", icon: "playground" },
  { key: "configure", label: "Configure", icon: "configure" },
];

export const secondaryAdminNavItems = [
  { key: "conversations", label: "Conversations", icon: "conversations" },
  { key: "analytics", label: "Analytics", icon: "analytics" },
];

export const knowledgeCards = [
  { title: "Suggestions", subtitle: "Knowledge to add from unanswered questions and past Inbox conversations", meta: "0 questions to review" },
  { title: "Website URL", subtitle: "Content imported from URLs, like knowledge bases or websites", meta: "3 pages" },
  { title: "Q&A", subtitle: "Questions and answers content", meta: "64 questions and answers" },
  { title: "Product database", subtitle: "Content from your products used for product recommendation", meta: "0 products" },
];

export const guidanceRows = [
  { name: "Tone of voice: Neutral", audience: "Everyone", note: "Controls the overall tone of the AI Agent." },
];

export const productBenefits = [
  { title: "Convert browsers into buyers", body: "Recommend the most relevant products based on what shoppers ask for" },
  { title: "Increase order value", body: "Suggest complementary items that naturally grow cart size." },
  { title: "Sell 24/7 inside chat", body: "Help customers discover and buy products without leaving the conversation." },
];

export const configureTabs = ["General", "Handoff", "Audiences", "Copilot"];

export const dataSourceRows = [
  ["FAQ url", "Website", "Main site", "Live", "Karina", "Apr 14, 2026, 4:01 PM"],
  ["Returns knowledge base", "Website", "Help center", "Live", "Karina", "Apr 14, 2026, 3:48 PM"],
  ["Shipping policy", "Website", "Docs", "Live", "Karina", "Apr 14, 2026, 3:22 PM"],
  ["Autumn bag catalog", "Website", "Storefront", "Live", "Emma", "Apr 13, 2026, 6:10 PM"],
  ["Product FAQ", "Q&A", "Support", "Live", "Emma", "Apr 13, 2026, 5:42 PM"],
  ["Messenger replies", "Website", "Messenger", "Live", "Emma", "Apr 12, 2026, 11:06 AM"],
  ["Warranty terms", "Website", "Docs", "Live", "Nina", "Apr 11, 2026, 9:18 AM"],
  ["Cancellations", "Q&A", "Support", "Live", "Nina", "Apr 10, 2026, 1:54 PM"],
  ["Autogenerated answers", "Q&A", "Inbox", "Live", "Marta", "Apr 10, 2026, 12:12 PM"],
  ["Website footer links", "Website", "Storefront", "Live", "Marta", "Apr 9, 2026, 6:33 PM"],
  ["Order issues", "Q&A", "Support", "Live", "Marta", "Apr 8, 2026, 2:17 PM"],
  ["Discount codes", "Q&A", "Storefront", "Live", "Lena", "Apr 8, 2026, 9:41 AM"],
];

export const actionTemplates = [
  { title: "Get order status from Shopify", body: "Empower customers to instantly check Shopify order status—payment, fulfillment, purchased products & tracking details—right in chat." },
  { title: "Book a call in Calendly", body: "Turn interest into meetings. Automatically offer visitors a personalized Calendly link whenever they ask to book a call." },
  { title: "Explore all templates", body: "Browse more ready-made automations and AI actions for your workflows." },
];

export const playgroundPrompts = [
  "What should I do if I need help with installation and adjusting Rip Crack products?",
  "How can I obtain an unlimited license?",
  "What is the policy regarding links to other websites on ripcrack.de?",
];

export const quickActions = [
  { title: "Live conversations", value: "12 unassigned", iconPath: "M6.5 7.5h11a1.5 1.5 0 0 1 1.5 1.5v6a1.5 1.5 0 0 1-1.5 1.5h-6l-3.5 2v-2H6.5A1.5 1.5 0 0 1 5 15V9a1.5 1.5 0 0 1 1.5-1.5Z" },
  { title: "Tickets", value: "0 unassigned", iconPath: "M9 12h6M9 9h3M6.5 5.5h8a2 2 0 0 1 2 2v11l-3-1.8-3 1.8-3-1.8-3 1.8v-11a2 2 0 0 1 2-2Z" },
  { title: "Lyro AI Agent", value: "Set up Lyro AI Agent", iconPath: "M12 5.2v1.6M12 17.2v1.6M18.8 12h-1.6M6.8 12H5.2M16.8 7.2l-1.2 1.2M8.4 15.6l-1.2 1.2M16.8 16.8l-1.2-1.2M8.4 8.4 7.2 7.2" },
  { title: "Flows", value: "7 active flows", iconPath: "M7 8h4M7 12h4M13 8h4M13 12h4M5 5.5h14a1.5 1.5 0 0 1 1.5 1.5v10a1.5 1.5 0 0 1-1.5 1.5H5A1.5 1.5 0 0 1 3.5 17V7A1.5 1.5 0 0 1 5 5.5Z" },
  { title: "Live visitors", value: "0 live visitors on your site", iconPath: "M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM3 12s3-5 9-5 9 5 9 5-3 5-9 5-9-5-9-5Z" },
];
